runtime: python39  

handlers:
  - url: /static
    static_dir: static
  - url: /
    static_files: index.html
    upload: index.html
  - url: /styles.css
    static_files: styles.css
    upload: styles.css
  - url: /profil.png
    static_files: https://storage.googleapis.com/dicoding-profile-web-bucket/profil.png
    upload: profil.png
